### ISSUE TITLE
BUG: Inbox icon indicator is buggy

### ISSUE THREAD

**Issue by Raymo111** [sarahkittyy/KeywordTracker#23]
The keyword matches icon/button that opens the inbox is sometimes red (shown) when there are no items in the inbox, and sometimes it is not shown when there are unread items in the inbox.

**Comment by sarahkittyy** [comment]
I already know about this, I actually didn't implement any sort of little "unread" indicator at all, it seems that the way I put the button there just. breaks discord :)
I'll fix it Eventually:tm:

**Comment by andylizi** [comment]
This is simply because the "Keyword Matches" button is cloned from the "Pinned Message" button, and if that button happens to have the unread indicator at that time, it would also be included.

https://github.com/sarahkittyy/KeywordTracker/blob/992959e9732acf79b9b66a00c289c61809477b5b/KeywordTracker.plugin.js#L388-L397

To fix it, just add this line:
```diff
       let inbox = pinned.cloneNode(true);
+      inbox.querySelector('span')?.remove();
       inbox.setAttribute('is-keyword-tracker-inbox', true);
       inbox.setAttribute('aria-label', 'Keyword Matches');
```

**Comment by sarahkittyy** [comment]
Added in 3a400339c5b2c4bd04b3b5085e6ecadc49bf6f67
