### ISSUE TITLE
[BUG] - KeywordTracker repeats messages with self trigger enabled

### ISSUE THREAD

**Issue by BigFlubba** [sarahkittyy/KeywordTracker#40]
Upon enabling self-testing causes messages to be repeated twice.

**How to reproduce**
Enable self-trigger, send keyword in chat

![image](https://user-images.githubusercontent.com/69104450/151645849-44a500cb-88bd-4160-8efe-164eb9bd7d3d.png)

**Comment by BigFlubba** [comment]
Also another bug I found related to it when clicking on your own trigger is when clicking on jump to message it goes to your friend list. I would personally use this feature as a bookmark to messages to look back at and such but is bugged.

**Comment by sarahkittyy** [comment]
Jumping to a ping automatically removes it from the inbox, and I don't intend to change that. May I suggest https://betterdiscord.app/plugin/PersonalPins for what you're looking for. As for the repeating notifications issue, I've noticed that too and will look into it, though it's luckily not too breaking a change because it's mostly for testing :)

**Comment by BigFlubba** [comment]
I would and have used it in the past, but I would have to use BDFBD and I don't want that. I get that.

**Comment by sarahkittyy** [comment]
What was I smoking when i responded to this,,, in v1.5.0 you don't mark messages as read for jumping to them that's a dumb feature
